# Derivatives as Finite Differences
========
### Task I

```{r include=FALSE}
require(mosaic)
```

My function is $f(x) = e^{-x/4} * sin(x)$

Here's the implementation in R:
```{r}
f <- function(x){exp(-x/4)*sin(x)}

Df <- D(exp(-x/4)*sin(x) ~ x)

evalD <- function(f, x) {
    h <- 1e-08  # 'Small h'
    return((f(x + h) - f(x - h))/(2 * h))
}

i <- function(x){evalD(f,x)}
j <- function(x){Df(x)}
plotFun(i(x)~x, x.lim= range(-1e-08, 1e-08), col='red')
plotFun(j(x)~x, x.lim= range(-1e-08, 1e-08), col='blue', add=TRUE)

plotFun(i(x)-j(x)~x, add=FALSE, x.lim= range(-1e-08, 1e-08), col='blue' )
```
The finite difference computation seems to be a good approximation because the plot shows that the lines are almost overlapping. 

### Task II

```{r}
f <- function(x){exp(-x/4)*sin(x)}

evalD2 <- function(f, x, h=1e-8) {
    return(function(x){(f(x + h) - f(x - h))/(2 * h)})
}
aFun <- evalD2(f,h=1e-20)
bFun <- evalD2(f,h=1e-15)
cFun <- evalD2(f,h=1e-10)
dFun <- evalD2(f,h=1e-5)
eFun <- evalD2(f,h=0.1)
fFun <- evalD2(f,h=1)

Df <- D(exp(-x/5)*cos(x) ~x)
j <- function(x){Df(x)}

```

```{r}
plotFun(aFun(x)~x, add=FALSE, x.lim= range(-1,1), col='blue')
plotFun(j(x)~x, add=TRUE,  col='blue')
```

```{r}
plotFun(bFun(x)~x, add=FALSE, x.lim= range(-1, 1), col='purple')
plotFun(j(x)~x, add=TRUE,  col='blue')
```

```{r}
plotFun(cFun(x)~x, add=FALSE, x.lim= range(-1, 1),  col='green')
plotFun(j(x)~x, add=TRUE, col='blue')
```

```{r}
plotFun(dFun(x)~x, add=FALSE, x.lim= range(-1, 1),  col='black')
plotFun(j(x)~x, add=TRUE, col='blue')
```

```{r}
plotFun(eFun(x)~x, add=FALSE, x.lim= range(-1, 1), col='brown')
plotFun(j(x)~x, add=TRUE, col='blue')
```

```{r}
plotFun(fFun(x)~x, add=FALSE, x.lim= range(-1,1), col='pink')
plotFun(j(x)~x, add=TRUE, col='blue')
```

### Task III
```{r}
evalD3 <- function(f, x) {
    h <-1e-8*abs(x)
    return((f(x + h) - f(x - h))/(2 * h))
}
evalD3fun <- function(x){evalD3(f,x)}
plotFun(evalD3fun(x)~x, x.lim= range(-10,10), add=FALSE, col='red')
plotFun(j(x)~x, add=TRUE, col='blue')


evalD4 <- function(f, x) {
    h <-1e-8*pmax(1,abs(x)) 
    return((f(x + h) - f(x - h))/(2 * h))
}

evalD4fun <- function(x){evalD4(f,x)}
plotFun(evalD4fun(x)~x, x.lim= range(-1, 1), add=FALSE, col='red')
plotFun(j(x)~x, add=TRUE, col='blue')
```

### Task IV
```{r}
f <- function(x){exp(-x/4)*sin(x)}

evalD <- function(f, x) {
    h <- 1e-08  # 'Small h'
    return((f(x + h) - f(x - h))/(2 * h))
}

myD <- function(f) {
    return(function(x) evalD(f, x))
}

myD <- function(f,h=1e-08){
  return(function(x) evalD2(f,x,h=h))
  }

myD(x^3)
```

### Task V
Second Derivative
```{r}
myD2 <- function(f,h){
  fprime <- myD(f,h=h)
  eprime <- myD(fprime,h=h)
  return(eprime)
}
```
Third Derivative
```{r}
myD3 <- function(f,h){
  fprime <- myD(f,h=h)
  eprime <- myD(fprime,h=h)
  return(myD(eprime,h=h))
}
```
Testing! 
```{r}
g20 <- myD2(f,1e-03) 
g30 <- myD3(f,1e-03) 

plotFun( g20(x)~x, x.lim=c(0,10),col='red')
plotFun( g30(x)~x, x.lim=c(0,10),col='blue',add=TRUE)


SecondD<-D(exp(-x/5)*sin(x)~x&x)
plotFun( g20(x)~x, x.lim=c(0,10),col='red')
plotFun(SecondD(x)~x,x.lim=c(0,10),col='blue',add=TRUE)

```

```{r}
ThirdD <-D(exp(-x/5)*sin(x)~x&x&x)
plotFun( g30(x)~x, x.lim=c(0,10),col='red')
plotFun(ThirdD(x)~x,x.lim=c(0,10),col='blue',add=TRUE)
```

```{r}
evalD3 <- function(f,x,h){
  return((f(x+h)-2*f(x)+f(x-h))/(h^2))
}
myD4 <- function(f,h=1e-5){
  return(function(x) evalD3(f,x,h=h))
  }

g50 <- myD4(f,1e-5)
plotFun( g50(x)~x, x.lim=c(0,10),col='red')
```
