# Indexing, Cropping, and Extending Images
=======
```{r}
require(mosaic)
require(COMP121)
require(png)
puppy <- readPNG(getURLContent("http://dtkaplan.github.io/ScientificComputing/Resources/Images/mindo.png"))
COMP121::canvas(x=c(1,220), y=c(1,220), asp=1)
rasterImage(puppy,1,1,216,198)
```
### 1. Mindo's Face! 
```{r}
COMP121::canvas(x=c(1,220), y=c(1,220), asp=1)
puppyface <- puppy[0:120, 90:210,]
rasterImage(puppyface, 1, 1, 216, 198)
```
### 2. Mindo's Front Left Paw! 
```{r}
COMP121::canvas(x= c(1,220), y= c(1,220), asp = 1)
puppyLeftPaw <- puppy[150:198, 1:50,]
rasterImage(puppyLeftPaw, 1, 1, 216, 198)
```
### 3. Mindo's Dog Tag! 
```{r}
COMP121::canvas(x= c(1,220), y= c(1,220), asp = 1)
puppydogtag <- puppy[120:140, 100:125,]
rasterImage(puppydogtag, 1, 1, 216, 198)
```
## Working on a Single Plane
```{r}
red <- puppy[,,1]
pair <- cbind(red, red)
canvas(x=c(1,2*216),y=c(1,198), asp=1)
rasterImage(pair, 1, 1, 2*216, 198)
```
Next: Framing
```{r}
framed <- cbind( red[,1:20], red, red[,197:216] )
canvas(x=c(1,40+216),y=c(1,198), asp=1)
rasterImage(framed, 1, 1, 40+216, 198)
```
Next: Reversed Borders
```{r}
framed <- cbind( red[,rev(1:20)], red, red[,rev(197:216)] )
canvas(x=c(1,40+216),y=c(1,198), asp=1)
rasterImage(framed, 1, 1, 40+216, 198)
```
Next: All four Sides Reversed Borders
```{r}
all4 <- rbind( framed[rev(1:20),], framed, framed[rev(179:198),])
canvas(x=c(1,40+216),y=c(1,40+198), asp=1)
rasterImage(all4, 1, 1, 40+216, 40+198)
```
### Putting Planes Together
```{r}
red   <- puppy[,,1]
green <- puppy[,,2]
blue  <- puppy[,,3]
weirdPuppy <- array( c(green,blue,red), dim=c(dim(red),3))
canvas( x=c(1,216), y=c(1,198), asp=1)
rasterImage(weirdPuppy,1,1,216,198)
```

MORE! 
```{r}
brighten <- function(photo, base=.50){
  b <- base + (1-base)*photo
  return(b)}
  
framing <- function(photo, width=20){
  s <- dim(photo)
  framed <- cbind( brighten(photo[,rev(1:width)]), photo, brighten(photo[,(s[2]:(1+s[2]-width))]))
  all4 <- rbind(brighten(framed[rev(1:width),]), framed, brighten(framed[s[1]:(1+s[1]-width),]))
  showimage(all4)
}

```

# More Framing Tasks
```{r}

ColorTheFrame <- function(photo, width=20, Neg=F, closetoBlue=F) {
   s <- dim(photo)
  array <- array(dim=c(2*width+s[1], 2*width+s[2],3)) 
  
   for (k in 1:3) {
     if ((k == 1) & (closetoBlue)){
        image <- photo[,,k]
  framed <- cbind( brighten(image[,rev(1:width)]), image, brighten(image[,(s[2]:(1+s[2]-width))] ))
  all4 <- rbind(brighten(framed[rev(1:width),]), framed, brighten(framed[s[1]:(1+s[1]-width),]))
        }
     else{
     
     image <- photo[,,k]
  framed <- cbind( image[,rev(1:width)], image, image[,(s[2]:(1+s[2]-width))] )
  all4 <- rbind(framed[rev(1:width),], framed, framed[s[1]:(1+s[1]-width),])
  
  array[,,k]<- all4 
   }}
   showimage(array)
   }
```
